# Generated by Django 5.0.1 on 2024-01-12 11:12

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=3)),
                ('symbol', models.CharField(blank=True, default='', max_length=3, null=True)),
                ('in_row_symbol', models.CharField(blank=True, default='', max_length=3, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('tags', models.JSONField(default=list)),
                ('images', models.JSONField(default=list)),
                ('is_best_seller', models.BooleanField(default=False)),
                ('category_tree', models.CharField(max_length=1024)),
                ('url', models.URLField(blank=True, max_length=1024, null=True)),
                ('brand_name', models.CharField(blank=True, max_length=255, null=True)),
                ('shipping_price', models.CharField(blank=True, max_length=255, null=True)),
                ('shipping_price_currency', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScrapeProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=255, unique=True)),
                ('progress', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('announcement', models.TextField(blank=True, null=True)),
                ('comment_count', models.IntegerField(blank=True, default=0, null=True)),
                ('total_sales', models.IntegerField(blank=True, default=0, null=True)),
                ('logo_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('admirers_count', models.IntegerField(blank=True, default=0, null=True)),
                ('owner_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_updated_announcement', models.DateTimeField(blank=True, null=True)),
                ('star_count', models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_variation_name', models.CharField(blank=True, max_length=255, null=True)),
                ('second_variation_name', models.CharField(blank=True, max_length=255, null=True)),
                ('first_variation_values', models.JSONField(blank=True, default=list, null=True)),
                ('second_variation_values', models.JSONField(blank=True, default=list, null=True)),
                ('has_variations', models.BooleanField(default=False)),
                ('has_combinations', models.BooleanField(default=False)),
                ('static_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('combination_prices', models.JSONField(blank=True, default=list, null=True)),
                ('currency', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crawler.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crawler.shop'),
        ),
    ]
